# Generated by Django 5.0.6 on 2024-05-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Answers', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_Areas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=255)),
                ('Subject_score', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('School_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
        migrations.AddField(
            model_name='class',
            name='Class',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='Name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
