# Generated by Django 5.0.6 on 2024-05-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_answers_assessment_areas_awards_student_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='Class',
            new_name='Class_name',
        ),
    ]
