# Generated by Django 5.0.6 on 2024-05-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_class_class_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='Answers',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='School_id',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='class_name',
        ),
        migrations.AddField(
            model_name='answers',
            name='Answer',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='Answer_Id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='Assessment_Areas_Id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='Awards_Id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='Category_Id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='Class_Id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='Correct_Answer',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='Correct_answer_percentage_per_class',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='Correct_asnwer_Id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='Participants',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='Student_Id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='Student_Score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='Subject_Id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='Year_level_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='sydney_participants',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='sydney_percentile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assessment_areas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Subject_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
