# Generated by Django 5.0.6 on 2024-05-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_answers_answers_remove_summary_school_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
