# Generated by Django 5.0.6 on 2024-05-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_answers_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='Class_name',
            new_name='Name',
        ),
    ]
